[package]
name = "tpt-e-typestate-hal"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Compile-time safe DMA & ISR abstractions for ESP32 family"
repository.workspace = true

[lints]
workspace = true

[dependencies]
esp-hal = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
mock = []
use_esp_hal = ["esp-hal"]

[package.metadata.docs.rs]
features = ["mock"]
